version: '3'
services:
  adminisbusy_app:
    build:
      context: app
      dockerfile: Dockerfile
    environment:
      - FLAG=SgffCTF{jwt_t0ken5_4r3_s1mpl3}
      - JWT_KEY=Abobik552
    ports:
      - 127.0.0.1:8081:8081
    restart: on-failure
    networks:
      - mynetwork

  adminisbusy_nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static/css:/static/css
      - ./app/static/js:/static/js
    ports:
      - 1488:80
    depends_on:
      - adminisbusy_app
    restart: on-failure
    networks:
      - mynetwork

networks:
  mynetwork:
