version: '3'
services:
  png2jpg_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8084:8084
    volumes:
      - shared_volume:/app/app/static
      - ./flag:/flag
    restart: on-failure
  png2jpg_nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - shared_volume:/static
    ports:
      - 5554:80
    depends_on:
      - png2jpg_app
    restart: on-failure

volumes:
  shared_volume: