version: '3'

services:
  app:
    build: .
    platform: linux/amd64
    cpus: 1
    mem_limit: 256m
    ports:
      - 5252:9003
    security_opt:
      - seccomp:./default.json
    restart: on-failure