version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLAG=SgffCTF{y4shch3ry_w1n5}
      - SESSION_SECRET=7f1a85d6-e6ce-4251-b775-6416d0828edd
    ports:
      - 127.0.0.1:3000:3000
    restart: on-failure
    networks:
      - mynetwork

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1400:80
    depends_on:
      - app
    restart: on-failure
    networks:
      - mynetwork

networks:
  mynetwork: